title: Welcome to Soham's playground
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: ""
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
url: 
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Soham Deshmukh # add your name
# author-img: david-freeman.jpg # add your photo
author-img: profile_pic.JPG
about-author: ECE masters student at CMU interested in using Signal Processing and Machine Learning to do cool stuff. Check out my Resume at https://www.slideshare.net/soham97/soham-deshmukh-resume # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: soham97 # add your Github handle
social-linkedin: soham-deshmukh-ba3865145 # add your Linkedin handle
social-email: soham0907@gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: UA-127734545-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
